import type {AppProps} from 'next/app'
import {GlobalStyle} from "@/style/global";
import React from "react";
import Head from "next/head";

export default function App({Component, pageProps}: AppProps) {
    return (
        <>
            <Head>
                <title>Designo</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <GlobalStyle/>
            <Component {...pageProps} />
        </>
    )
}
