import Head from 'next/head'
import React from "react";
import {ColorButton, GlobalStyle, H1, H2, H3, Paragraph, WhiteButton} from "@/style/global";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/assets/favicon-32x32.png"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Jost:wght@400;500&display=swap"
                      rel="stylesheet"/>
            </Head>
            <GlobalStyle/>
            <main>
                <div>
                    <div>
                        Hello TS!
                    </div>
                </div>
            </main>
        </>
    )
}
