import Head from 'next/head'
import React from "react";
import {GlobalStyle} from "@/style/global";
import MainLayout from "@/layouts/MainLayout";
import Hero from "@/components/home/Hero";
import SectionNav from "@/components/SectionNav";
import MainSection from "@/components/home/MainSection";
import {GetStaticProps} from "next";
import {CardsProps} from "@/interfaces/app_interfaces";

export default function Home({home_cards}: CardsProps) {
    return (
        <>
            <Head>
                <title>Designo</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/assets/favicon-32x32.png"/>

            </Head>
            <GlobalStyle/>
            <MainLayout>
                <>
                    <Hero/>
                    <SectionNav/>
                    <MainSection home_cards={home_cards}/>
                </>
            </MainLayout>
        </>
    )
}

export const getStaticProps: GetStaticProps = async (context) => {
    const {home_cards} = await import('@/data/data.json')
    return {
        props: {home_cards},
    }
}