import Head from 'next/head'
import React from "react";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/assets/favicon-32x32.png"/>
            </Head>
            <main>
                <div>
                    Hello TS!
                </div>
            </main>
        </>
    )
}
